# Introduction {#intro}

The introduction chapter needs to state the objectives of the program of research, include definitions of the key concepts and variables and give a brief outline of the background and research approach. The aim of the introduction is to contextualise the proposed research.
In the opening paragraph, give an overall view of what is included in the chapter. For example:
This chapter outlines the background (section \@ref(background)) and context (section \@ref(context)) of the research, and its purposes (section \@ref(purposes)). Section \@ref(significance) describes the significance and scope of this research and provides definitions of terms used. Finally, section \@ref(outline) includes an outline of the remaining chapters of the thesis.




## Background {#background}

Give the background of the problem to be explored in your study and what led you to doing the thesis. For example, you might discuss educational trends related to the problem, unresolved issues, social concerns. You might also include some personal background.

## Context {#context}

Outline the context of the study (i.e., the major foci of your study) and give a statement of the problem situation (basic difficulty – area of concern, felt need).

## Purposes {#purposes}

Define the purpose and specific aims and objectives of the study. Emphasise the practical outcomes or products of the study. Delineate the research problem and outline the questions to be answered or the overarching objectives to be achieved.

## Significance, Scope and Definitions {#significance}


Discuss the importance of your research in terms of the topic (problem situation), the methodology, and the gap in the literature. Outline the scope and delimitations of the study (narrowing of focus).
Define and discuss terms to be used (largely conceptual here; operational definitions may follow in Research Design chapter).

## Thesis Outline {#outline}

Outline the chapters for the remainder of your thesis.
