# (PART) Literature Review {.unnumbered}

# Literature Review

The literature review chapter should demonstrate a thorough knowledge of the area and provide arguments to support the study focus. The aim of the literature review chapter is to delineate various theoretical positions and from these to develop a conceptual framework for generation of hypotheses and setting up the research question. The literature review chapter needs to:

* Critically evaluate the literature rather than merely describe previous literature (i.e., what is good/bad about the body of literature?).
*	Show a synthesis and be integrated rather than being more like an annotated bibliography.
*	Identify key authors and the key works in the area, thus acquainting the reader with existing studies relative to what has been found, who has done work, when and where latest research studies were completed and what approaches to research methodology were followed (literature review of methodology sometimes saved for chapter on methodology).
*	Constitute an argument.
*	Clearly identify the gap in the literature that is being addressed by the research question.  

Suitable sources for the literature review include:

*	General integrative reviews cited that relate to the problem situation or research problem such as those found in psychological and sociological reviews of research.
*	Specific books, monographs, bulletins, reports, and research articles – preference shown in most instances for literature of the last 10 years.
*	Unpublished materials (e.g., dissertations, theses, papers presented at recent professional meetings not yet in published form, etc.).

The literature review chapter can be arranged in terms of the questions to be considered or objectives/purposes set out in the Introduction chapter.   
Start with an overview of this chapter by outlining the topics to be discussed. For example [your thesis may have more than 3 topics and therefore more sections]:   

This chapter begins with a historical background [optional] (section \@ref(history)) and reviews literature on the following topics: [topic 1] (section 2.2) [briefly describe the topic]; [topic 2] (section 2.3) [briefly describe the topic]; and [topic 3] (section 2.4) [briefly describe the topic]. Section 2.5 highlights the implications from the literature and develops the conceptual framework for the study.


##	Historical Background {#history}

According to Linnaeus, the earth was covered with water except some mountain peaks and these mountain peaks were first colonized by plants and animals. As water level comes down and peaks were emerged new biota has colonized and diversified (Lomolino, 2001). Willdenow (1805) was the first to associate the elevational pattern of species diversity to climate and speculated that warmer regions have more diversity (Lomolino, 2001; Willdenow, 1805). Later, Hocker (1956) has also associated distribution of climatic factors to distribution limits of Pinus taeda L. (Hocker, 1956). According to the theory of island biogeography (MacArthur & Wilson, 1967), the mountains are simply comparable to islands that are isolated from others and therefore due to smaller area and high extinction rates on the mountain tops should have lower species diversity. The observed decline in species richness along the elevation in Crete island supports this view and area alone explains a significant amount of variation in species richness along the elevational gradient (Trigas et al., 2013).

##	TOPIC 1
Present and discuss your first topic.

##	TOPIC 2
Present and discuss your second topic.

##	TOPIC 3
Present and discuss your third topic.

##	SUMMARY AND IMPLICATIONS
Summarise the literature review and discuss the implications from the literature for your study – the theoretical framework for your study. Here you can make an explicit statement of the hypotheses, propositions or research questions and how they are derived from existing theory and literature. Establish from the literature (or gap in the literature) the need for this study and the likelihood of obtaining meaningful, relevant, and significant results. Outline any conceptual or substantive assumptions, the rationale and the theoretical framework for the study. Explain the relationships among variables or comparisons, and issues to be considered. This section should demonstrate the contribution of the research to the field, and be stated in a way that leads to the methodology.

The literature was surveyed from available databases such as Web of Science, Google Scholar, ScienceDirect and relevant journals such as Nature, Science, Global Change Biology, Ecology, Ecology Letters, Journal of Biogeography, Global Ecology and Biogeography etc. Keywords such as ‘Plant range shifts’, ‘climate change’, ‘elevation’ OR ‘altitude’ and their combinations with suitable operators i.e. AND, OR, NOT were used for literature search. 
Origin and Evolution of the Field: Bibliometrix analysis
Altitude, Elevation or Height? Bibliometrics
Indicators of Climate Change in Himalayas? Glaciers
