--- 
title: "Climate-driven Elevational Shifting of Plant Distributions in the selected sites of Siwaliks of north-western India"
author: "Abhishek Kumar"
date: "`r Sys.Date()`"
site: bookdown::bookdown_site
output: bookdown::gitbook
linestretch: 1.5
fontsize: 12pt
toc-depth: 1
lof: True
lot: True
documentclass: book
bibliography: [book.bib, packages.bib]
biblio-style: apalike
csl: apa.csl
link-citations: yes
github-repo: abhikumar86/phd-thesis
url: 'http\://abhikumar86.github.io/phd-thesis/'
description: "This is a minimal example of using the bookdown package to write a book. The output format for this example is bookdown::gitbook."
---

# Preface {-}


# Acknowledgements {.unnumbered}

I feel privileged and lucky to have received a great deal of support and assistance from all the generous people around me. I am grateful to almighty God for good health and wellbeing during the course of my whole research work.\
I express my heartfelt gratitude to my supervisor, **Dr. Anand Narain Singh**, Department of Botany, Panjab University, Chandigarh for his invaluable expertise, immense knowledge, patience and motivation throughout the process. This research work has never been accomplished without his continuous guidance, dedicated involvement, immense faith and understanding over these past five years.\
I am extremely thankful and indebted to the **Prof. Harsh Nayyar**, **Prof. Sunita Kapila** and **Prof. Daizy Rani Batish**, the chairpersons, Department of Botany, Panjab University Chandigarh for providing all necessary facilities during the entire course of this work. I take this opportunity to express gratitude to all of the Department faculty members for their help and support. I also thank all the non-teaching and technical staff of the department for their unceasing encouragement, support and attention.\
I must express my sincere acknowledgements to my cooperative lab members for their wonderful collaboration. I would particularly like to single out my co-worker *Meenu Patil* for her unfailing support, continuous help, regular motivation, patience and strength she gave me throughout my years of study and through the process of researching and writing this thesis. I could not have completed this thesis without the support of my friends, who provided happy distractions to rest my mind outside of my research.\
Most importantly, none of this could have happened without the support and encouragement of my family offered through phone calls and gatherings. This thesis stands as a testament to our unconditional love and encouragement. You are always there for me. I sincerely acknowledge University Grants Commission (UGC), New Delhi for providing financial assistance in the form of Junior- and Senior Research Fellowships. Finally, I also place on record, my sense of gratitude to everyone, who directly or indirectly, have lent their hand in this venture.\

```{block2, type='flushright', html.tag='p'}
Abhishek Kumar   
Chandigarh, India
```


# Abstract {.unnumbered}

There is a high consensus that the average global temperature has been increasing due to anthropogenic activities only during the last century. This phenomenon has significantly affected functioning of ecosystems and almost all the ecosystems are now facing notable changes. Thus, many of the species have shifted to suitable habitats (either elevational or latitudinal) due to pressure posed by the changing environment. While animals can move as warming happens but plants are stationary organisms and cannot move; so, the difference in the distribution of various plant life stages can be an indication that plants are responding to climate change effects.\
Although the impacts of climate change on the biodiversity have been documented globally, but limited information is available about such impacts on plant diversity of low-elevation Himalayan region. Improved understanding is urgently needed to assess how these changes cascade into the distributions of species in space and time, and ultimately, what they might mean for the low elevation ecosystems. Therefore, such information is very important as these low-elevation environments are expected to be among most susceptible to ongoing climate change. This vulnerability highlights the importance of identifying the key drivers of elevational plant richness pattern as well as the landscape architecture that support the persistence of species populations and richness.\
This synopsis is the proposed research plan of my PhD research work that could be helpful to fill these gaps in the research. I will address the following key objectives: (i) Examining diversity pattern along elevational gradient, (ii) Examining distribution pattern along elevational gradient and, (iii) Detecting any shifts in distributions and correlating with changing environmental conditions. The outcomes of this research work might be useful for policy makers and effective conservation of species that are sensitive to climate change. Moreover, this can provide a baseline data for plant distribution and diversity patterns in relation to impacts of climate change.

# About the Author {.unnumbered}

[Abhishek Kumar](https://akumar.netlify.app/) is a senior research fellow at the Soil Ecosystem and Restoration Ecology Lab in the Department of Botany, Panjab University, Chandigarh. His research interests include the responses of ecological structure and functions to climate change, and he is currently working on the elevational pattern of plant distributions and diversity in the Siwalik Ecosystem.
